### ISSUE TITLE
Can you tell me how to Install and configure this with burrow.

### ISSUE THREAD

**Issue by pavansai8** [tulios/burrow-stats#5]

**Comment by tulios** [comment]
Sure, we run burrow-stats with docker but feel free to run it in the machine directly. Burrow-stats has a configuration file where you configure the burrow endpoints, something like this:

```json
{
  "consumers": [
    {
      "name": "consumer_name_1",
      "status": "http://burrow-host:8000/v2/kafka/cluster_name/consumer/consumer_name_1/status",
      "consumer_group_offset": "http://burrow-host:8000/v2/kafka/cluster_name/consumer/consumer_name_1/topic/topic_name_1",
      "topic_offset": "http://burrow-host:8000/v2/kafka/cluster_name/topic/topic_name_1"
    }
  ]
}
```

following the attributes:
* name: The name you want to display in burrow-stats for this consumer
* status: The status endpoint in burrow, <burrow host>/v2/kafka/<cluster name>/consumer/<consumer name>/status. You should be able to call this directly in burrow.
* consumer_group_offset and topic_offset follow the same logic as status

You can check a full example of this configuration file here: [configs.json.example](https://github.com/tulios/burrow-stats/blob/master/configs.json.example)

The project is already in docker hub but you can copy the Dockerfile in this repo if you want. Burrow-status accepts an env variable (PORT), an example of the docker command would be:

```sh
docker run \
  -p 8022:8022 \
  -e PORT=8022 \
  -v /path/to/your/configs.json:/opt/burrow-stats/configs.json \
  tulios/burrow-stats:latest
```

**Comment by pavansai8** [comment]
Hi,

Thanks for your response.
But I don't have docker installed on my linux machine. Is there any other way I can do this installation. I really liked the UI. So trying to implement the same for our burrow.

**Comment by tulios** [comment]
An example of our configuration in burrow (burrow.cfg):

```ini
; https://github.com/linkedin/Burrow/wiki/Configuration

; The [general] configuration heading covers the location of log and PID files,
; as well as some shared configuration for Kafka clusters.
[general]
logdir=/var/log
logconfig=/opt/burrow/burrow-log.xml
pidfile=burrow.pid
client-id=<our client id>
group-blacklist=(^(console-consumer-|python-kafka-consumer-).*$)|(.*influxdb_tracer)

; The [zookeeper] heading specifies a Zookeeper ensemble to use in order to provide
; locking between multiple copies of Burrow. This allows you to run multiple copies
; of Burrow with only one being allowed to execute the notifiers at any time.
[zookeeper]
hostname=zookeeper1.example.com
hostname=zookeeper2.example.com
hostname=zookeeper3.example.com
port=2181
timeout=6
lock-path=/burrow/notifier

; The [kafka] heading specifies a single Kafka cluster for Burrow to connect to
; and monitor. The subheading ("local" in the example below) is the name of the
; Kafka cluster that is used to identify it in HTTP requests and notifications.
; Multiple [kafka] headings can be specified to provide for monitoring many Kafka
; clusters with one Burrow instance.
[kafka "us"]
broker=kafka.example.com
broker-port=9092
zookeeper=zookeeper1.example.com
zookeeper=zookeeper2.example.com
zookeeper=zookeeper3.example.com
zookeeper-port=2181
zookeeper-path=/
zookeeper-offsets=true
offsets-topic=__consumer_offsets

; The [tickers] heading holds configurations regarding how often to execute
; certain actions.
[tickers]
broker-offsets=60

; The [lagcheck] heading holds configurations regarding the internal lag checking algorithm.
; For more information about how these configurations are used, please see the Consumer
; Lag Evaluation Rules page. (https://github.com/linkedin/Burrow/wiki/Consumer-Lag-Evaluation-Rules)
[lagcheck]
; How many consumer offsets to store for a partition. This determines the window over which to evaluate consumer lag.
intervals=10
expire-group=604800
min-distance=1
; How frequently, in seconds, to scan Zookeeper committed offsets for clusters that are configured for ZK offsets.
zookeeper-interval=60
zk-group-refresh=300

; The [httpserver] heading configures the HTTP endpoint in Burrow.
[httpserver]
server=on
port=8000

; https://github.com/linkedin/Burrow/wiki/Email-Notifier
; https://github.com/linkedin/Burrow/wiki/HTTP-Notifier
```

**Comment by tulios** [comment]
hi @pavansai8, yes it is. You need to install node.js, then clone the repo and follow the commands:

```sh
npm install
npm run build
```

**Comment by pavansai8** [comment]
let me try installing that bro. I'm new to these things.
And I have the same burrow configuration on my side. I will have few more issues regarding this burrow like E-mail. lag , max lag. Will you able to help me?

**Comment by pavansai8** [comment]
Thanks Tulios. Here is one issue

Burrow is not showing lag and max lag as null always. Can someone help me on this. I have stopped my consumer and sent number of messages from producer side still the lag and max lag are showing as null. 
I'm using Advanced Rest client to send http request.
Below is the request and response.

http://nj09mhf5527.mhf.mhc:8000/v2/kafka/DevCluster/consumer/testgroup90/lag

{
"error": false
"message": "consumer group status returned"
"status": {
"cluster": "DevCluster"
"group": "testgroup90"
"status": "ERR"
"complete": true
"partitions": [1]
0: {
"topic": "topic03"
"partition": 0
"status": "STOP"
"start": {
"offset": 145
"timestamp": 1471419404000
"lag": 0
}-
"end": {
"offset": 145
"timestamp": 1471419404000
"lag": 0
}-

}-

"partition_count": 1
"maxlag": null
"totallag": 0
}-
"request": {
"url": "/v2/kafka/DevCluster/consumer/testgroup90/lag"
"host": "nj09mhf5527.mhf.mhc"
"cluster": "DevCluster"
"group": "testgroup90"
"topic": ""
}-
}

**Comment by pavansai8** [comment]
I'm getting this error while runing npm install from burrow-stats-master folder.
drwxr-xr-x 5 root root   4096 Jul 19 16:58 client
drwxr-xr-x 2 root root   4096 Jul 19 16:58 bin
[root@nj09mhf5529 burrow-stats-master]# npm install
npm WARN package.json burrow-stats@0.6.0 No repository field.
npm WARN deprecated babel@6.5.2: Babel's CLI commands have been moved from the babel package to the babel-cli package

**Comment by pavansai8** [comment]
Hi Tulios,

Seems it got installed successfully after that. Can you tell me how can I launch the UI.

**Comment by pavansai8** [comment]
[root@nj09mhf5529 burrow-stats-master]# npm run build

> burrow-stats@0.6.0 build /home/pbhaskaruni/burrow-stats-master
> rm -rf dist/ && node bin/build.js

Build success!
 What should I run after this on Tulios?

**Comment by tulios** [comment]
great! you can run `NODE_ENV=production npm start` to launch the server

**Comment by pavansai8** [comment]
I'm getting this error tulios.

ERROR: Configuration file is missing, please create a "configs.json" in the root folder. Expecting path:  
/home/pbhaskaruni/burrow-stats-master/configs.json

**Comment by pavansai8** [comment]
Forgot. I got that. I will keep you posted.

**Comment by pavansai8** [comment]
Tulios,

This is the error now.

 NODE_ENV=production npm start

> burrow-stats@0.6.0 start /home/pbhaskaruni/burrow-stats-master
> node bin/server.js

module.js:339
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (routes.js:1:15)
    at Module._compile (module.js:435:26)
    at loader (/home/pbhaskaruni/burrow-stats-master/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/pbhaskaruni/burrow-stats-master/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

npm ERR! Linux 2.6.18-308.el5
npm ERR! argv "/home/pbhaskaruni/node-v4.2.1-linux-x64/bin/node" "/home/pbhaskaruni/node-v4.2.1-linux-x64/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! burrow-stats@0.6.0 start: `node bin/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the burrow-stats@0.6.0 start script 'node bin/server.js'.
npm ERR! This is most likely a problem with the burrow-stats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls burrow-stats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pbhaskaruni/burrow-stats-master/npm-debug.log
[root@nj09mhf5529 burrow-stats-master]#

**Comment by tulios** [comment]
I think you need at least no 5.5

**Comment by pavansai8** [comment]
which product version you are talking about tulios?

**Comment by pavansai8** [comment]
are you saying about node js? Which version you suggest tulios?

**Comment by pavansai8** [comment]
Tulios, 
It is the same error with 6.2.1 also
module.js:442
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (routes.js:1:15)
    at Module._compile (module.js:541:32)
    at loader (/home/pbhaskaruni/burrow-stats-master/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/pbhaskaruni/burrow-stats-master/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

npm ERR! Linux 2.6.18-308.el5
npm ERR! argv "/home/pbhaskaruni/node-v6.2.1-linux-x64/bin/node" "/home/pbhaskaruni/node-v6.2.1-linux-x64/bin/npm" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! burrow-stats@0.6.0 start: `node bin/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the burrow-stats@0.6.0 start script 'node bin/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the burrow-stats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs burrow-stats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls burrow-stats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pbhaskaruni/burrow-stats-master/npm-debug.log
[pbhaskaruni@nj09mhf5529 burrow-stats-master]$

**Comment by tulios** [comment]
ok, I'm taking a look

**Comment by tulios** [comment]
So `request` was not being used but it is working locally, anyway I removed the unused require (is already in master, just pull).

Try again with:
```sh
NODE_ENV=production npm run build
NODE_ENV=production npm start
```

**Comment by pavansai8** [comment]
Sorry, You want me to download the code again?

**Comment by tulios** [comment]
yes, I've made a change to remove one unused import

**Comment by pavansai8** [comment]
ok I will downoad it again. Thanks.

**Comment by pavansai8** [comment]
Still same erro Tulios. :(

[pbhaskaruni@nj09mhf5529 burrow-stats-master]$
[pbhaskaruni@nj09mhf5529 burrow-stats-master]$ NODE_ENV=production npm run build

> burrow-stats@0.6.0 build /home/pbhaskaruni/burrow-stats-master
> rm -rf dist/ && node bin/build.js

Build success!
[pbhaskaruni@nj09mhf5529 burrow-stats-master]$ NODE_ENV=production npm start

> burrow-stats@0.6.0 start /home/pbhaskaruni/burrow-stats-master
> node bin/server.js

module.js:561
    throw err;
    ^

SyntaxError: /home/pbhaskaruni/burrow-stats-master/configs.json: Unexpected token n in JSON at position 41
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:558:27)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (configs.js:1:14)
    at Module._compile (module.js:541:32)
    at loader (/home/pbhaskaruni/burrow-stats-master/node_modules/babel-register/lib/node.js:148:5)

npm ERR! Linux 2.6.18-308.el5
npm ERR! argv "/home/pbhaskaruni/node-v6.2.1-linux-x64/bin/node" "/home/pbhaskaruni/node-v6.2.1-linux-x64/bin/npm" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! burrow-stats@0.6.0 start: `node bin/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the burrow-stats@0.6.0 start script 'node bin/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the burrow-stats package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs burrow-stats
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls burrow-stats
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pbhaskaruni/burrow-stats-master/npm-debug.log

**Comment by pavansai8** [comment]
IT is throwing like this If I give npm run dev.

SyntaxError: /home/pbhaskaruni/burrow-stats-master/configs.json: Unexpected token n in JSON at position 41
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:558:27)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (configs.js:1:14)
    at Module._compile (module.js:541:32)
    at loader (/home/pbhaskaruni/burrow-stats-master/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/pbhaskaruni/burrow-stats-master/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
Program node bin/server.js exited with code 1

Starting child process with 'node bin/server.js'
Received SIGINT, killing child...
 
And can you tell me what is the UI url for this one?

**Comment by tulios** [comment]
@pavansai8 it is complaining about your configuration file (`configs.json`), can you review it?
`Unexpected token n in JSON at position 41`

It's complaining that the configs file is incorrect.

**Comment by pavansai8** [comment]
I  checked it tulios. It is fine.

[pbhaskaruni@nj09mhf5529 burrow-stats-master]$ vi configs.json
{
  "consumers": [
    {
      "name": ""name": "testgroup12349",
      "status": "http://nj09mhf5529.mhf.mhc:8000/v2/kafka/DevCluster/consumer/testgroup12349/status",
      "consumer_group_offset": "http://nj09mhf5529.mhf.mhc:8000/v2/kafka/DevCluster/consumer/testgroup12349/topic/devtopic4",
      "topic_offset": "http://nj09mhf5529.mhf.mhc:8000/v2/kafka/DevCluster/topic/devtopic4"
    },
    {
      "name": "testgroup1234978",
      "status": "http://nj09mhf5529.mhf.mhc:8000/v2/kafka/DevCluster/consumer/testgroup1234978/status",
      "consumer_group_offset": "http://nj09mhf5529.mhf.mhc:8000/v2/kafka/DevCluster/consumer/testgroup1234978/topic/topic02",
      "topic_offset": "http://nj09mhf5529.mhf.mhc:8000/v2/kafka/DevCluster/topic/topic02"
    }
  ],
  "chartOptions": {
    "scaleOverride": false,
    "scaleFontSize": 14,
    "scaleSteps": null,
    "scaleStepWidth": null,
    "scaleStartValue": null
  },
  "burrowStatsOptions": {
    "pollInterval": 60,
    "cacheBinSize": 30
  }
}

**Comment by pavansai8** [comment]
Tulios,

It worked.

pbhaskaruni@nj09mhf5529 burrow-stats-master]$ NODE_ENV=development npm start

> burrow-stats@0.6.0 start /home/pbhaskaruni/burrow-stats-master
> node bin/server.js

Server started on port 8031
webpack built 7cf2e06d2e09745b2dfa in 7701ms


:) :) :)

**Comment by tulios** [comment]
Super! 👍 

I think I'll add some steps of this thread into the readme to make it easier for other users.
Thanks!

**Comment by pavansai8** [comment]
It is taking time to refresh the current status. :(

**Comment by pavansai8** [comment]
But the UI is really great. Can I know at what time interval the UI gets refresh?
Can you tell me how to understand the graph in consumer lag area.

**Comment by tulios** [comment]
@pavansai8 you can configure with the `pollInterval` property, take a look at the [example file](https://raw.githubusercontent.com/tulios/burrow-stats/master/configs.json.example)

**Comment by pavansai8** [comment]
Hi Tulios,

I'm back again. I have started the burrow-stats today. And I have started one consumer
UI is throwing API failed! Dashborad offline error. What should I do for this?

**Comment by pavansai8** [comment]
Can I change the pollinterval value to 10 seconds?

**Comment by pavansai8** [comment]
Hi Tulios,

You there? I'm couple of more issues facing with burrow. Can you help me.

**Comment by tulios** [comment]
what is happening?

**Comment by pavansai8** [comment]
Not related with burrow-stats. It is regarding kafka burrow which I mentioned to you yesterday. Will you help me?
